//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Easy_TravelsEntities : DbContext
    {
        public Easy_TravelsEntities()
            : base("name=Easy_TravelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accountant> Accountants { get; set; }
        public virtual DbSet<BookedHotel> BookedHotels { get; set; }
        public virtual DbSet<BookedVehicle> BookedVehicles { get; set; }
        public virtual DbSet<HotelBooking> HotelBookings { get; set; }
        public virtual DbSet<Inq> Inqs { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<VehicleBooking> VehicleBookings { get; set; }
        public virtual DbSet<AccountantList> AccountantLists { get; set; }
    }
}
